

services:
  shopus:
    container_name: shopus
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres_shopus
    env_file:
      - shopus.env
    ports:
      - 8010:8000
    networks:
      - shopus

  postgres_shopus:
    container_name: postgres_shopus
    build:
      context: build/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - 5555:5432
    networks:
      - shopus

networks:
  shopus:
    name: shopus

volumes:
  postgres: