

services:
  shopus1:
    container_name: shopus1
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - postgres_shopus1
    env_file:
      - shopus.env
    ports:
      - 8011:8000
    networks:
      - shopus1

  postgres_shopus1:
    container_name: postgres_shopus1
    build:
      context: build/postgres
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
    volumes:
      - "postgres1:/var/lib/postgresql/data"
    ports:
      - 5556:5432
    networks:
      - shopus1

networks:
  shopus1:
    name: shopus1

volumes:
  postgres1: